### ISSUE TITLE
Build failing with the latest version

### ISSUE THREAD

**Issue by szymanp1** [bitrise-steplib/bitrise-step-android-unit-test#14]
After updating to 0.10.0 the step fails at the end with:

```
Export test results for test addon:
panic: runtime error: index out of range
goroutine 1 [running]:
main.getUniqueDir(0xc00030dc20, 0x56, 0xc00001e1a8, 0x2f, 0xc000020600, 0xd)
	/tmp/bitrise-go-toolkit393823558/src/github.com/bitrise-steplib/bitrise-step-android-unit-test/testaddon.go:30 +0x628
main.main()
	/tmp/bitrise-go-toolkit393823558/src/github.com/bitrise-steplib/bitrise-step-android-unit-test/main.go:215 +0x142a
```
Works fine on 0.9.6

**Comment by lszucs** [comment]
Hi,

Thanks for reporting you issue! Can you please provide a build URL?

**Comment by szymanp1** [comment]
@lszucs here you go: https://app.bitrise.io/build/c48b9a5753556ffa

**Comment by lszucs** [comment]
Thanks!

We found the cause of the error and will start working on a fix right away. I will update you once the fix is released.

**Comment by Krigu** [comment]
Same issue here. 

In our builds it seems to happen only with multi-project builds.

**Comment by lszucs** [comment]
@szymanp1, @Krigu

Please make the following modifications in your affected workflow to test the fix.

1) use custom branch of the android unit test step

In the workflow editor, go to the manual `bitrise.yml` editor view and change the step id `android-unit-test@0.10.0` to `git::https://github.com/bitrise-steplib/bitrise-step-android-unit-test@quickfix-index-out-of-bounds-error`, for example:

```
  primary:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.14: {}
    - cache-pull@2.0.1: {}
    - script@1.1.5:
        title: Do anything with Script step
    - install-missing-android-tools@2.3.5:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - android-lint@0.9.6:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - module: "$MODULE"
        - variant: "$VARIANT"
    - git::https://github.com/bitrise-steplib/bitrise-step-android-unit-test@quickfix-index-out-of-bounds-error:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - module: "$MODULE"
        - variant: "$VARIANT"
    - deploy-to-bitrise-io@1.3.19: {}
    - cache-push@2.1.1: {}
```

2) enable debug mode

Add an environment variable `is_debug` with value `yes`. Both the name and value must be lowercase. It doesn't matter if it is an app or workflow level var, but a workflow level var is best.
If you edit the `bitrise.yml` directly, take care to specify the value as `is_debug: 'yes'` (and NOT `isdebug: yes`) 
I 

Once done, rerun your failing workflow. You should see a log entry `Debug mode enabled` and all the artifact paths that are being matched for exporting should also be printed. Hopefully the step will succeed, if not, I'll need you to paste the build URL for inspecting the artifact paths.
